### ISSUE TITLE
fix travis for python 2.7 with ROOT

### ISSUE THREAD

**Issue by TaiSakuma** [alphatwirl/alphatwirl#45]
- https://travis-ci.org/alphatwirl/alphatwirl/builds/412573877
  - error with Python 2.7 with ROOT
  - while installing scandir, required by pytest

**Comment by TaiSakuma** [comment]
- tried installing scandir with conda, but didn't work https://travis-ci.org/alphatwirl/alphatwirl/builds/412604443
  - conda installed scandir 1.7 https://anaconda.org/conda-forge/scandir
  - pip install pytest tries install scandir 1.8
  - scandir 1.8 was released only 3 days ago: https://pypi.org/project/scandir/#history
  - can try again when scandir 1.8 becomes available in conda-forge.

**Comment by TaiSakuma** [comment]
- tried adding `psutil`:  https://travis-ci.org/alphatwirl/alphatwirl/jobs/412703068
- based on the comparison with [cms-l1t-analysis](https://github.com/cms-l1t-offline/cms-l1t-analysis) done by @kreczko
- in [.travis.yml](https://github.com/alphatwirl/alphatwirl/blob/716f1e446db2b2c1a13b9ba568b4c4f28341b507/.travis.yml), added the following line to the section of `install`
```yaml
     - conda install -y -q psutil`
```
- and, added the section of `addons`
```yaml
addons:
  apt:
    packages:
    - build-essential
    - python-psutil
```

**Comment by TaiSakuma** [comment]
- checking the miniconda version
    - `Miniconda3-latest-Linux-x86_64.sh` currently points to `Miniconda3-4.5.4-Linux-x86_64.sh`
    - all versions can be browsed here: https://repo.continuum.io/miniconda/

**Comment by TaiSakuma** [comment]
tried using the same version of miniconda as in [cms-l1t-analysis](https://github.com/cms-l1t-offline/cms-l1t-analysis), i.e., Miniconda2-4.1.11-Linux-x86_64.sh
- still error https://travis-ci.org/alphatwirl/alphatwirl/jobs/412723798

**Comment by kreczko** [comment]
Do you want me to have a go? It is probably a minor detail hidden in the recipe

**Comment by TaiSakuma** [comment]
Thank you.

Now it works: https://travis-ci.org/alphatwirl/alphatwirl/builds/412736640

I made the order of the install commands the same as in [cms-l1t-analysis](https://github.com/cms-l1t-offline/cms-l1t-analysis): https://github.com/alphatwirl/alphatwirl/commit/3f09a68c806a880b8ad143ae1303d3bd1f14bf1a

**Comment by TaiSakuma** [comment]
The issue is resloved - thanks to @kreczko 
- all tests pass. failures in python 2.7 with root are no longer allowed
- https://travis-ci.org/alphatwirl/alphatwirl/builds/412740518

**Comment by TaiSakuma** [comment]
probably not resolved. [travis log](https://travis-ci.org/alphatwirl/alphatwirl/jobs/412740519) and [codecov](https://codecov.io/gh/alphatwirl/alphatwirl/tree/da11f39e133046d45d9060fa9bcb812e5f16fb34/tests/unit/roottree) indciate that `import ROOT` is raising `ImportError`.

**Comment by TaiSakuma** [comment]
- reverted https://github.com/alphatwirl/alphatwirl/commit/e47f83d43ff8087587e20eb11565c6958de64de4
- leave this issue open

**Comment by TaiSakuma** [comment]
- the tests started passing again today https://travis-ci.org/alphatwirl/alphatwirl/jobs/415150556
- i didn't change anything

**Comment by TaiSakuma** [comment]
- the error doesn't happen anymore.
- stopped allowing failures:  https://github.com/alphatwirl/alphatwirl/commit/b2e8601073208b415e999d9dc955a6c09b02e677#diff-354f30a63fb0907d4ad57269548329e3
