### ISSUE TITLE
ValueError with duplicate datasets

### ISSUE THREAD

**Issue by shane-breeze** [alphatwirl/alphatwirl#50]
## Release version
 0.16.0 (expected to appear in 0.20.0 as well)

## Issue
`ValueError` is raised on [loop/merge.py#L7](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/merge.py#L7) when duplicate datasets (two or more dataset entries with the same `name` attribute)

## Description
Duplicate datasets can appear by user error. The final duplicate dataset will overwrite all the other in [loop/EventDatasetReader.py#L74](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/EventDatasetReader.py#L74), but [loop/EventDatasetReader.py#L68](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/EventDatasetReader.py#L68) is filled with `runids` from all dataset duplicates.

When the code reaches [loop/merge.py#L7](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/merge.py#L7) it tries to access runids from duplicate datasets that have been overwritten in [loop/EventDatasetReader.py#L74](https://github.com/alphatwirl/alphatwirl/blob/master/alphatwirl/loop/EventDatasetReader.py#L74)

## Resolution
Everything works fine if there are no duplicate datasets.

However, this could be checked or enforced somewhere earlier.

**Comment by TaiSakuma** [comment]
- I didn't assume that dataset names can be duplicate. That is because the idea of `dataset` in alphatwirl originally came from `component` in heppy. Heppy components never have duplicate names because they are used as directory names.
- Now, a dataset in alphatwirl can be generally considered as a set of files. I don't see a reason why not the duplicate is not allowed. It should be allowed.
- What should happen when names are duplicate?
    - Because the dataset names become a column of the output dataframe, in order for the output to make sense, all datasets with the same name should be considred as the same dataset. If datasets with the same name are treated as different datasets, categoreis in the output will have duplicate entreis, which won't makse sense.

**Comment by TaiSakuma** [comment]
- fixed in [v0.20.1](https://github.com/alphatwirl/alphatwirl/tree/v0.20.1)

**Comment by TaiSakuma** [comment]
Thank you for the repost. I will close this issue. I recommend to use v0.20.1, which will appear in [pypi](https://pypi.org/project/alphatwirl/0.20.1/) shortly.

Please let me know if it is not possible to upgrade to v0.20.1 and need to use v0.16.0 or any other older versions.

**Comment by shane-breeze** [comment]
Cheers. I think it'll be possible to use v0.20.1. I'll notify you if not
