### ISSUE TITLE
Add support for SGE batch systems

### ISSUE THREAD

**Issue by benkrikler** [alphatwirl/alphatwirl#8]
I've no idea how much work this would involve, but to bring alphatwirl out to more sites, support beyond HTCondor would be nice to be able to run components in parallel.  In particular, sun grid engine batch systems, although somewhat old-fashioned, are still common such as lxplus or on the Imperial College batch system.

**Comment by TaiSakuma** [comment]
This is straightforward to implement. 

What needs to be done is to develop a `dispatcher`  for each batch system. Two dispatchers have been implemented so far: `HTCondorJobSubmitter` and `SubprocessRunner`. Both are in [`concurrently`](https://github.com/alphatwirl/alphatwirl/tree/v0.9.5/alphatwirl/concurrently). A dispatcher needs to be given to `TaskPackageDropbox` at the initialization.

**Comment by shane-breeze** [comment]
See #23

**Comment by TaiSakuma** [comment]
this is realized as a separate package [atsge](https://pypi.org/project/atsge/).
