### ISSUE TITLE
Extend the contents used for DataFrame filenames 

### ISSUE THREAD

**Issue by benkrikler** [alphatwirl/alphatwirl#9]
This is based on a series of posts first made to Slack. But for the TL;DR:

* The TableFileNameComposer class currently creates filenames that contain only the binning scheme for the DFs
* Sometimes the same binning scheme will be used whilst other variables are changed to create a DF (eg, for systematics, where we change the weighting or corrections).
* I suggest we have TableFileNameComposer.__call__() receive the full DF config specification, such that any generic filename composer one would like to create has the full amount of information available to it.  So on [this line](https://github.com/alphatwirl/alphatwirl/blob/v0.9.x/alphatwirl/configure/TableConfigCompleter.py#L80), you would just pass in `ret`:
```py
ret['outFileName'] = self.createOutFileName(ret)
```

For the meantime, I have a hacky solution to my problem, which can be used instead of TableFileNameComposer:
```py
class WithInsertTableFileNameComposer():                                           
    def __init__(self, composer, inserts):                                         
        self.inserts = inserts                                                     
        self.composer = composer                                                   
        self.frame_idx = 0                                                         
                                                                                   
    def __call__(self, columnNames, indices, **kwargs):                                     
        this_insert = self.inserts[self.frame_idx]                                 
        suffix = kwargs.get("suffix", self.composer.default_suffix)      
        kwargs["suffix"] = "--{}.{}".format(this_insert, suffix)                   
        self.frame_idx += 1                                                        
        return self.composer(columnNames, indices, **kwargs)     
```

**Comment by TaiSakuma** [comment]
I will close this. It has been inactive for a while. Please reopen if this is still an issue.

**Comment by benkrikler** [comment]
I don't think this has been solved and we still rely on my hacky solution within FAST-RA1 so I would like to re-open this issue.  However, it seems I do not have permissions to do this, in which case I can make a new issue, or perhaps @TaiSakuma you are able.

**Comment by TaiSakuma** [comment]
I would consider that the issue has been solved. `TableFileNameComposer` is just a little helper function (functor, technically) that composes a file name from table configuration. Using this function is optional. Users can just give file names to table configurations without using this function. They can do so by manually typing names or creating another function that generates file names.  If I understand correctly, a function (or functor) that produces file names was created and is being used in FAST-RA1.  Then, there isn't an issue here.
